### ISSUE TITLE
Playbooks fails on java installation

### ISSUE THREAD

**Issue by vasili439** [andrewrothstein/ansible-keycloak#1]
Hi!

Version: 1.0.3

Playbook fails during jre installation: 

> TASK [andrewrothstein.java-oracle : download tgz...] ***************************
> fatal: [opsv0018]: FAILED! => {"changed": false, "dest": "/tmp/jre-8u192-linux-x64.tar.gz", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://download.oracle.com/otn-pub/java/jdk/8u192-b12/750e1c8617c5452694857ad95c3ee230/jre-8u192-linux-x64.tar.gz"}

I guess you need to update meta/main.yaml:

```
  - role: andrewrothstein.java-oracle-jre
    version: v2.1.2
```

to: 

```
  - role: andrewrothstein.java-oracle-jre
    version: v2.1.3
```

**Comment by andrewrothstein** [comment]
fix published to the galaxy as v1.0.4
