### ISSUE TITLE
standalone.sh ignores profile.d

### ISSUE THREAD

**Issue by MCPDanilovich** [andrewrothstein/ansible-keycloak#2]
If i am installing keycloak using your role, systemd unit isn't starting.

<Apr 11 15:15:42  systemd: Started The WildFly Application Server.
Apr 11 15:15:47  systemd: Reloading.
Apr 11 15:15:48  systemd: Started The WildFly Application Server.
Apr 11 15:15:48  launch.sh: =========================================================================
Apr 11 15:15:48  launch.sh: JBoss Bootstrap Environment
Apr 11 15:15:48  launch.sh: JBOSS_HOME: /opt/wildfly
Apr 11 15:15:48  launch.sh: JAVA: java
Apr 11 15:15:48  launch.sh: JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
Apr 11 15:15:48  launch.sh: =========================================================================
Apr 11 15:15:48  launch.sh: /opt/wildfly/bin/standalone.sh: line 330: java: command not found>

java and jre added to default environment:
![image](https://user-images.githubusercontent.com/25364749/55971431-222b0e00-5c8a-11e9-9b70-ee22e29897b7.png)
<[root@ ~]# ls -la /etc/profile.d/ | grep orac
-rw-r--r--  1 root root   71 Apr 11 18:10 java-oracle.sh
-rw-r--r--  1 root root   32 Apr 11 18:10 oracle-jre.sh>

When i added to /etc/wildfly/wildfly.conf JAVA_HOME, installation was completed
<# The configuration you want to run
WILDFLY_CONFIG=standalone.xml

JAVA_HOME=/usr/local/java

# The mode you want to run
WILDFLY_MODE=standalone

# The address to bind to
WILDFLY_BIND=0.0.0.0>

**Comment by andrewrothstein** [comment]
This role's purpose is simply to install the necessary software. My strategy is usually to create a separate role for configuring the installation. If ur curious for an example, take a look at my zookeeper-cluster and/or kafka-broker roles. These are both java based and use the /usr/local/java/oracle-jre.env file to introduce JAVA_HOME into the systemd unit's environment. I just haven't gotten that far with keycloak.
